name: flash-frontend staging

on:
  push:
    branches:
      - staging

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: npm install, build, and test
      run: |
        npm install
        npm install --save-dev dotenv
        envsubst "`printf '${%s} ' $(sh -c "env|cut -d'=' -f1")`" < ./.env.example > ./.env
        echo "$(cat ./.env)"
        npm run build
      env:
        CI: false
        DOMAIN: https://admin-api-staging.flash.health/api/v1
        DOMAIN_ODOC: https://dev.gen2.odoc.life/healthPartner/v1/healthPartnerExternalRequests
        TOKEN_ODOC: rlAZ95kmA3LKXn52QzRuty6iiiKrrfmMjMdCHtoQs4Zzwcnz3o
        ACTIVITY_TRACKER_HOST: https://activity-track-staging.flash.health/api/v1
        ACTIVITY_TRACKER_TOKEN: 42g7pyhx-e7zu-ru5x-afvpa-p2naq3x4xe9a

    - name: Upload statics & Cloudfront CDN cache clear
      run: |
        aws s3 sync ./build s3://admin-staging.flash.health
        aws cloudfront create-invalidation --distribution-id E30ULPZX9IIR24 --paths '/*'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-south-1'